### ISSUE TITLE
[Release] 0.1.0 issue tracking

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx-addons#127]
Please comment or link any issues you find with tfx-addons 0.1.0.

Thanks.

**Comment by casassg** [comment]
Release candidate 2 - https://github.com/tensorflow/tfx-addons/releases/tag/v0.1.0rc2
`pip install tfx-addons==0.1.0rc2`

**Comment by hanneshapke** [comment]
@casassg Can we close this issue?

**Comment by casassg** [comment]
yes, thats fair
