### ISSUE TITLE
Add feature_selection component?

### ISSUE THREAD

**Issue by rcrowe-google** [tensorflow/tfx-addons#160]
The [feature selection component](https://github.com/tensorflow/tfx-addons/tree/main/tfx_addons/feature_selection) doesn't seem to be an active module:

```
tfx_addons._ACTIVE_MODULES

['__version__',
 'mlmd_client',
 'schema_curation',
 'feast_examplegen',
 'xgboost_evaluator',
 'sampling',
 'message_exit_handler']
```

Can we add it?

**Comment by rcrowe-google** [comment]
@deutranium

**Comment by casassg** [comment]
We need a set of needed deps added here: https://github.com/tensorflow/tfx-addons/blob/main/tfx_addons/version.py#L49
