### ISSUE TITLE
Integration with HuggingFace Hub

### ISSUE THREAD

**Issue by deep-diver** [tensorflow/tfx-addons#172]
Hi folks (cc: @rcrowe-google , @sayakpaul)

as you know, HuggingFace provides [Hub](https://huggingface.co/docs/hub/index) to host models and prototype applications. I think this is a nice place for some reasons:

1. If the model is compatible to 🤗 [Transformer](https://huggingface.co/docs/transformers/index), the model can be easily loaded up and used with the library. In these days, lots of ML practitioners are familiar with the usage of `Transformers`.
 
2. HuggingFace Hub comes with [Git-LFS](https://git-lfs.github.com/) feature out of the box, so it is a good place to store the large size of model files with version controls in Git manner.

3. HuggingFace Space let us write simple applications with [Gradio](https://gradio.app/) and [Streamlit](https://streamlit.io/), and it provides a VM to serve the applications. The VM spec is not great, but it can be improved over time. Also, before the actual production releases of the model, we can let people to play with the experimental versions of the model, and get some feedback.

To this end, I want to propose two components:
- `HFModelPusher` : It pushes a model from an upstream TFX component such as `Trainer` to the HuggingFace Model Hub

- `HFSpacePusher` : It pushes an application codes to the HuggingFace Space Hub. This is intended to work as the downstream step of the `HFModelPusher`. Some placeholders in the application template codes will be replaced with the outputs of the `HFModelPusher` such as `model_repo_id`, `model_version`

Below image shows how they are interconnected

![tmp](https://user-images.githubusercontent.com/26025527/186041471-37df5904-ef91-4c61-b70e-6d88921c9d49.jpeg)

**Comment by sayakpaul** [comment]
Adding @***@***.*** ***@***.***> from Hugging Face to the
conversation.
Sayak Paul | sayak.dev

**Comment by deep-diver** [comment]
#174 for the first component

**Comment by rcrowe-google** [comment]
These sound like valuable components to have for folks who are working with HF tools and models.

**Comment by rcrowe-google** [comment]
When you're ready, please submit a project proposal.

**Comment by deep-diver** [comment]
@rcrowe-google 

actually, the project proposal has been merged a while ago. the thing is I have suggested two separate custom components, but we decided to merge two into one.

https://github.com/tensorflow/tfx-addons/blob/main/proposals/20220823-huggingface_model_pusher.md
