### ISSUE TITLE
MultiModelPusher

### ISSUE THREAD

**Issue by deep-diver** [tensorflow/tfx-addons#199]
TF Serving supports hosting multiple models in one place. I want to discuss if it is a useful to pushes multiple models from multiple `Trainers`?

**Comment by hanneshapke** [comment]
@deep-diver Thank you for your submission. Just a clarification: What's the benefit over having n Pusher components in a pipeline?

**Comment by deep-diver** [comment]
I am not sure yet, but TFServing supports this feature, so I thought there might be some good usecases. For instance, 1. training slightly different models => serve them for A/B testing, 2. or just simply serve the model from current pipeline along with the last one for A/B testing.
