### ISSUE TITLE
Run linter into sklearn_example to make sure it can be run under CI

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx-addons#61]
## Expected Behavior

Currently sklearn pylint/isort/yapf is not working for sklearn_example. We should either consolidate the CI for that and the rest of the project or figure out a good strategy to maitain those.

CC @TheMichaelHu

**Comment by TheMichaelHu** [comment]
qq is the config you're using for pylint from https://google.github.io/styleguide/pyguide.html#21-lint ?

**Comment by casassg** [comment]
I'm actually using https://github.com/tensorflow/tfx/blob/master/pylintrc

**Comment by casassg** [comment]
Btw, this is the errors getting in sklearn: https://github.com/tensorflow/tfx-addons/runs/3244621362#step:4:73

YAPF/Isort is mostly stylistic stuff to avoid some of the pylint issues. We can skip them for certain examples (or we can just run them to format it)
